[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["qtakamitsu <qtakamitsu@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0-beta1", features = ["mysql"] }
diesel_infer_schema = { version = "1.0.0-beta1", features = ["mysql"] }
dotenv = "0.9.0"
